bind=Alt,space,spawn_shell,vicinae toggle || vicinae server
bind=SUPER,v,spawn,vicinae deeplink vicinae://launch/clipboard/history
bind = super,period,spawn,vicinae deeplink vicinae://launch/core/search-emojis


bind=SUPER,q,spawn,ghostty
bind=SUPER+SHIFT,q,spawn,kitty
bind = super,e,spawn,yazi
