
##############################
### WINDOWS AND WORKSPACES ###
##############################

# See https://wiki.hyprland.org/Configuring/Window-Rules/ for more
# See https://wiki.hyprland.org/Configuring/Workspace-Rules/ for workspace rules\
windowrule = float,class:^vivaldi(-stable)?$,title:Save File
# I don't know below
windowrule = float,class:^()$,title:^()$

# Ref https://wiki.hyprland.org/Configuring/Workspace-Rules/
# "Smart gaps" / "No gaps when only"
# uncomment all if you wish to use that.
# workspace = w[tv1]s[false], gapsout:0, gapsin:0
# workspace = f[1]s[false], gapsout:0, gapsin:0
# windowrule = bordersize 0, floating:0, onworkspace:w[tv1]s[false]
# windowrule = rounding 0, floating:0, onworkspace:w[tv1]s[false]
# windowrule = bordersize 0, floating:0, onworkspace:f[1]s[false]
# windowrule = rounding 0, floating:0, onworkspace:f[1]s[false]

# app launchers
windowrule = float, tag:launcher
windowrule = pin, tag:launcher
windowrule = center, tag:launcher
windowrule = stayfocused, tag:launcher
windowrule = dimaround on, tag:launcher
# windowrule = decorate off, tag:launcher
windowrule = noblur, tag:launcher
windowrule = noborder, tag:launcher
windowrule = noshadow, tag:launcher

# file picker
windowrule = float,class:^(xdg-desktop-portal-gtk)$
windowrule = center,class:^(xdg-desktop-portal-gtk)$

# 1Password
windowrule = float,class:^(1Password)$
windowrule = center,class:^(1Password)$
windowrule = float,class:^(1Password)$,title:(Quick Access)
windowrule = center,class:^(1Password)$,title:(Quick Access)
windowrule = nomaxsize, class:^(1Password)$, focus:1
windowrule = minsize 25% 55%, class:^(1Password)$
windowrule = bordercolor rgb(b4befe), class:^(1Password)$, focus:1

windowrule = bordercolor rgb(a6e3a1),class:^(1Password)$,title:^(Quick Access).*
windowrule = minsize 25% 55%,class:^(1Password)$,title:^(Quick Access).*

# PiP
windowrule = float,title:^(Picture in picture)$
windowrule = content video,title:^(Picture in picture)$
windowrule = pin,title:^(Picture in picture)$
windowrule = opacity 0.7 0.5,title:^(Picture in picture)$
windowrule = dimaround,title:^(Picture in picture)$,focus:1
windowrule = move onscreen cursor 100%-w-20 0-10,title:^(Picture in picture)$

# Ignore maximize requests from apps. You'll probably like this.
windowrule = suppressevent maximize, class:.*

# Fix some dragging issues with XWayland
windowrule = nofocus,class:^$,title:^$,xwayland:1,floating:1,fullscreen:0,pinned:0


# gaming + below 
windowrule = float, class:^(steam_app_\d+)$

# known vulkan tiling bug: https://www.reddit.com/r/hyprland/comments/1ms0cza/comment/n91x9tf/?utm_source=share&utm_medium=web3x&utm_name=web3xcss&utm_term=1&utm_content=share_button
# windowrule = float, class:^(dev.zed.Zed)$
# windowrule = float, title:^(vkcube)$

# calculator apps - nice floaty widget-like
windowrule = float, class:.*(?i)([c|q]alc).*

windowrule = float, class:^(swayimg)$
windowrule = center, class:^(swayimg)$


# debuggers
windowrule = float, class:^(wev)$
windowrule = center, class:^(wev)$
windowrule = maxsize 500 500, class:^(wev)$
windowrule = size 500 500, class:^(wev)$
