exec-once = quickshell --config noctalia-shell
exec-once = vicinae server
exec-once = 1password --silent --enable-features=UseOzonePlatform --ozone-platform=wayland
exec-once = heroic
exec-once = surge server
exec-once = goignis init
exec-once = steam -silent
exec-once = discord --start-minimized

# exec-once = awww daemon
